### ISSUE TITLE
otns crashes while adding a new router first time

### ISSUE THREAD

**Issue by Nitin-iotina** [openthread/ot-ns#199]
otns code info
------------------------
branch: main
Commit ID: 2ed1042116de035585c057f3195b69f9588d3382

openthread code info:
-------------------------
branch: main
commit ID: 3fdaaab07c2dc3d322d0b4f8a31c812330be6e3a

Steps to reproduce:
-------------------------
I am following below tutorial for otns
https://openthread.io/codelabs/openthread-network-simulator

below are the error logs which gets produced after executing add router command:
```
ubuntu20:~/Desktop/workspace/openthread/output/simulation/bin$ otns
> warn  2022-01-31 20:48:07.672 - grpcwebproxy exit unexpectedly: exit status 1, try restarting ...
> 
> add router x 300 y 100
panic	2022-01-31 20:49:22.809 - expect node 1's extaddr to be valid, but failed
panic	2022-01-31 20:49:22.810 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:1038
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				dispatcher.go:898
	            				simulation.go:107
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1581
	Error:      	Should be true

panic: 2022-01-31 20:49:22.809 - expect node 1's extaddr to be valid, but failed
	panic: 2022-01-31 20:49:22.810 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:1038
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				dispatcher.go:898
	            				simulation.go:107
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1581
	Error:      	Should be true


goroutine 29 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000e0c60, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x486
go.uber.org/zap.(*SugaredLogger).log(0xc0000a6168, 0x4, {0xc0002ccfc0, 0xc00089f630}, {0xc0000ca4c0, 0x10000000000020f, 0x7fded59a0e38}, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0x13b
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf({0xa29e0c, 0x3}, {0xc0002948f0, 0x1, 0x201})
	/home/nitin/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x16e
github.com/simonlingoogle/go-simplelogger.assertLogger.Errorf(...)
	/home/nitin/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:199
github.com/stretchr/testify/assert.Fail({0xaeb840, 0xf9cce8}, {0xa318a8, 0xe}, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:262 +0x384
github.com/stretchr/testify/assert.True({0xaeb840, 0xf9cce8}, 0x2, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:657 +0x8e
github.com/simonlingoogle/go-simplelogger.AssertTrue(...)
	/home/nitin/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:227
github.com/openthread/ot-ns/simulation.(*Node).inputCommand(0xc00010c080, {0xa2a3b0, 0x4})
	/home/nitin/Desktop/workspace/otns/simulation/node.go:191 +0x65
github.com/openthread/ot-ns/simulation.(*Node).Exit(0xc00010c080)
	/home/nitin/Desktop/workspace/otns/simulation/node.go:165 +0x2e
github.com/openthread/ot-ns/simulation.(*Simulation).Stop(0xc0001d0af0)
	/home/nitin/Desktop/workspace/otns/simulation/simulation.go:162 +0xa5
panic({0x95e0e0, 0xc000294780})
	/home/nitin/Downloads/go/src/runtime/panic.go:1038 +0x215
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000e0c60, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x486
go.uber.org/zap.(*SugaredLogger).log(0xc0000a6168, 0x4, {0xc0000d69c0, 0xc0002ea5c0}, {0xc0000ca1c0, 0x0, 0xc00089fbe0}, {0x0, 0x0, 0x0})
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0x13b
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/home/nitin/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf({0xa48e78, 0x30}, {0xc00089fc98, 0x1, 0x1193841960})
	/home/nitin/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x16e
github.com/openthread/ot-ns/dispatcher.(*Dispatcher).AddNode(0xc000174a80, 0x27, 0xc000055d38, 0x2, 0x0)
	/home/nitin/Desktop/workspace/otns/dispatcher/dispatcher.go:898 +0x245
github.com/openthread/ot-ns/simulation.(*Simulation).AddNode(0xc0001d0af0, 0xc0000340c0)
	/home/nitin/Desktop/workspace/otns/simulation/simulation.go:107 +0x20c
github.com/openthread/ot-ns/cli.(*CmdRunner).executeAddNode.func1(0xc00008e1e0)
	/home/nitin/Desktop/workspace/otns/cli/CmdRunner.go:317 +0x2a
github.com/openthread/ot-ns/cli.(*CmdRunner).postAsyncWait.func1()
	/home/nitin/Desktop/workspace/otns/cli/CmdRunner.go:266 +0x2d
github.com/openthread/ot-ns/dispatcher.(*Dispatcher).Run(0xc000174a80)
	/home/nitin/Desktop/workspace/otns/dispatcher/dispatcher.go:232 +0x410
github.com/openthread/ot-ns/simulation.(*Simulation).Run(0xc0001d0af0)
	/home/nitin/Desktop/workspace/otns/simulation/simulation.go:136 +0x13b
created by github.com/openthread/ot-ns/otns_main.Main
	/home/nitin/Desktop/workspace/otns/otns_main/otns_main.go:174 +0x3a7

```

**Comment by Vinggui** [comment]
I could not reproduce this issue here. Maybe it is already fixed, or you modified the code?

**Comment by simonlingoogle** [comment]
This is a classic issue where OTNS can't add OpenThread simulation nodes with `VIRTUAL_TIME_UART=0`. 

It has always been a burden for OTNS to support both VIRTUAL_TIME_UART=1 and VIRTUAL_TIME_UART=0. 

We used to have another issue in non VIRTUAL_TIME_UART=0 where a single device can't become Leader within 3 seconds duration. I think VIRTUAL_TIME_UART=0 mode is inherently flawed and harder to comprehend since the OT simulation node has multiple inputs and outputs (IO and simulation events). 

Maybe it's simpler to only support VIRTUAL_TIME_UART=1 ? 

Thoughts? @jwhui

**Comment by jwhui** [comment]
I don't recall the use case for supporting `VIRTUAL_TIME_UART=0`. @simonlingoogle , can you remind me?

Unless there is a strong use case I'm forgetting, I think it's fine to only support `VIRTUAL_TIME_UART=1`.

**Comment by simonlingoogle** [comment]
> I don't recall the use case for supporting `VIRTUAL_TIME_UART=0`. @simonlingoogle , can you remind me?

there is no obvious use case. It was mainly for convenience so that users can worry less about OT build flags.

**Comment by jwhui** [comment]
OK. I'm OK to only support `VIRTUAL_TIME_UART=1`. We just have to make that clear in documentation. I agree it will make things simpler.

**Comment by simonlingoogle** [comment]
Yes, we need to revise the codelab https://openthread.io/codelabs/openthread-network-simulator along the way. 

One way to facilitate building openthread for otns is to provide a dedicated command for that. https://github.com/openthread/ot-ns/pull/223 is trying to implement that.

**Comment by jwhui** [comment]
Closing stale issue.
